[project]
src = "src"
dot_env = ".env"

# [networks.pyevm]

[networks.anvil]
url = "http://127.0.0.1:8545"
save_to_db = false
prompt_live = false
default_account_name = "anvil0"
unsafe_password_file = "~/.moccasin/unsafe-passwords/anvil0" # ONLY FOR DUMMY ACCOUNT

[networks.sepolia]
url = "$SEPOLIA_URL"
save_to_db = false
default_account_name = "metamask_dev"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"

[networks.sepolia-zksync]
url = "$ZKSYNC_SEPOLIA_URL"
chain_id = 300
save_to_db = false
default_account_name = "metamask_dev"
explorer_uri = "https://explorer.sepolia.era.zksync.dev"
explorer_type = "zksyncexplorer"
is_zksync = true

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
