[project]
src = "src"

[networks.anvil]
url = "http://127.0.0.1:8545"
save_to_db = false
prompt_live = false

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
